ServerName localhost
ServerTokens Prod
ServerSignature Off
KeepAliveTimeout 2

<IfModule mpm_prefork_module>
    StartServers 1
    MinSpareServers 1
    MaxSpareServers 2
    ServerLimit 2
    MaxRequestWorkers 2
    MaxConnectionsPerChild 1000
</IfModule>

<VirtualHost *:__PORT__>
    DocumentRoot /var/www/html/public
    <Directory /var/www/html/public>
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
    </Directory>
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
